_shared:
  storageClass: &storageClass "do-block-storage"

namespace: n8n-application

postgresql:
  global:
    storageClass: *storageClass

  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "17.4.0"

  architecture: replication

  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: *storageClass

#    resources:
#      requests:
#        memory: "512Mi"
#        cpu: "250m"
#      limits:
#        memory: "2Gi"
#        cpu: "1"

    podSecurityContext:
      enabled: true
      fsGroup: 1001

    containerSecurityContext:
      enabled: true
      runAsUser: 1001

  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      size: 10Gi
      storageClass: *storageClass

#    resources:
#      requests:
#        memory: "512Mi"
#        cpu: "250m"
#      limits:
#        memory: "2Gi"
#        cpu: "1"

  auth:
    enablePostgresUser: true
    existingSecret: "postgresql-secret"
    database: "mydatabase"
  tls:
    enabled: true
    autoGenerated: true

  service:
    type: ClusterIP
    port: 5432

  networkPolicy:
    enabled: true
    allowExternal: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  backup:
    enabled: true
    schedule: "0 2 * * *" # Daily at 2 AM
    retentionDays: 7
    storage:
      type: spaces
      digitalocean:
        bucket: "my-pg-backups"
        region: "ams1"
        existingSecret: "do-spaces-secret"
