apiVersion: v2
name: n8n-application
description: "Helm Chart for deploying n8n on Kubernetes, a fair-code workflow automation platform with native AI capabilities for technical teams. Easily automate tasks across different services."
type: application
version: 1.0.1
appVersion: "1.81.4"
dependencies:
  - name: n8n
    version: 1.0.5
    repository: oci://8gears.container-registry.com/library
  - name: postgresql
    version: 16.5.6
    repository: https://charts.bitnami.com/bitnami
  - name: common-helpers
    repository: oci://ghcr.io/webgrip/common-charts
    version: 1.0.13
