namespace: n8n-application

_shared_config:
  hostname: &hostname n8n.staging.k8s.webgrip.nl
  url: &url https://n8n.staging.k8s.webgrip.nl/

n8n:
  enabled: true
  image:
    repository: webgrip/n8n-application
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    className: ingress-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-traefik
      traefik.ingress.kubernetes.io/router.middlewares: "ingress-traefik-ryan-basic-auth@kubernetescrd"
    hosts:
      - host: *hostname
        paths:
          - "/"
    tls:
      - secretName: letsencrypt-n8n-application
        hosts:
          - *hostname

  main:
    config:
      webhook_url: *url
      generic_timezone: Europe/Amsterdam
      node_env: production
      queue_health_check_active: true
      n8n:
        host: *hostname
        log_level: debug
        log_output: console,file
        log_file_location: /logs/n8n.log
        metrics: true
        runners_enabled: true
        personalization_enabled: false
        enforce_settings_file_permissions: true
        templates_enabled: true
        hiring_banner_enabled: false
      db:
        type: postgresdb
        postgresdb:
          host: n8n-application-postgresql.n8n-application.svc.cluster.local
          port: 5432
          database: n8n_db
          user: n8n

    extraEnv:
      N8N_ENCRYPTION_KEY:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secrets
            key: n8n-encryption-key
      DB_POSTGRESDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secrets
            key: postgres-password
      OPENAI_API_KEY:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secrets
            key: openai-api-key
      TELEGRAM_API_KEY:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secrets
            key: telegram-api-key
      DISCORD_BOT_TOKEN:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secrets
            key: discord-bot-token
      N8N_PUBLIC_API_KEY:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secrets
            key: n8n-public-api-key

postgresql:
  architecture: standalone

  auth:
    username: n8n
    database: n8n_db
    existingSecret: n8n-application-secrets
    secretKeys:
      userPasswordKey: postgres-password

  metrics:
    enabled: true

  primary:
    service:
      type: ClusterIP
      ports:
        postgresql: 5432

