namespace: application-application

_shared_config:
  hostname: &hostname application-application.staging.k8s.webgrip.nl
  url: &url https://application-application.staging.k8s.webgrip.nl

application:
  enabled: true

  controllers:
    main:
      pod:
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          fsGroup: 1500
          fsGroupChangePolicy: OnRootMismatch

      containers:
        app:
          image:
            repository: docker.io/webgrip/application-application
            tag: "latest"
            pullPolicy: Always
          # securityContext:
          #   runAsUser: 1500
          #   runAsGroup: 1500
          #   allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          probes:
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - sh
                    - -lc
                    - >
                      php -v >/dev/null && \
                      nc -z application-application-mariadb 3306 && \
                      nc -z application-application-redis-master 6379 && \
                      nc -z 127.0.0.1 4200
                initialDelaySeconds: 10
                periodSeconds: 10
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - sh
                    - -lc
                    - >
                      php -v >/dev/null && \
                      nc -z application-application-mariadb 3306 && \
                      nc -z application-application-redis-master 6379 && \
                      nc -z 127.0.0.1 4200
          env:
            # App
            - name: APP_NAME
              value: application-application
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: *url
            - name: APP_LOCALE
              value: en
            - name: APP_FALLBACK_LOCALE
              value: en
            - name: APP_TIMEZONE
              value: Europe/Amsterdam
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: application-application-secrets
                  key: app-key

            - name: DB_STRICT
              value: "false"
            - name: REQUIRE_HTTPS
              value: "true"
            - name: TRUSTED_PROXIES
              value: "**"

            - name: LOG_CHANNEL
              value: stderr
            - name: LOG_LEVEL
              value: info

            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: application-application-mariadb.application-application.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: application-application
            - name: DB_USERNAME
              value: application-application
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-application-secrets
                  key: mariadb-password

            - name: SESSION_DRIVER
              value: redis
            - name: CACHE_DRIVER
              value: redis
            - name: QUEUE_CONNECTION
              value: redis
            - name: REDIS_CLIENT
              value: phpredis
            - name: REDIS_PREFIX
              value: application-application_
            - name: REDIS_HOST
              value: application-application-redis-master.application-application.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-application-secrets
                  key: redis-password

            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: application-application-secrets
                  key: api-secret
            - name: UPDATE_SECRET
              valueFrom:
                secretKeyRef:
                  name: application-application-secrets
                  key: update-secret

        web:
          image:
            repository: nginxinc/nginx-unprivileged
            tag: 1.29.1-alpine3.22-perl
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: http
                initialDelaySeconds: 5
                periodSeconds: 10
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: http
                initialDelaySeconds: 2
                periodSeconds: 5

  service:
    main:
      controller: main
      ports:
        http:
          enabled: true
          port: 80
          targetPort: http

  ingress:
    main:
      enabled: true
      className: ingress-traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-traefik
        traefik.ingress.kubernetes.io/router.middlewares: ingress-traefik-ryan-home-ip-allow-list@kubernetescrd
      hosts:
        - host: *hostname
          paths:
            - path: /
              service:
                identifier: main
                port: http
      tls:
        - secretName: letsencrypt-application-application
          hosts:
            - *hostname

  persistence:
    public:
      type: persistentVolumeClaim
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: do-block-storage

redis:
  enabled: true
  image:
    repository: bitnamilegacy/redis
    tag: "8.2.1"
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    enabled: true
    existingSecret: application-application-secrets
    existingSecretPasswordKey: redis-password
  master:
    persistence:
      enabled: true
      size: 1Gi
    disableCommands: [FLUSHALL, CONFIG, KEYS]
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "150m"
      memory: "256Mi"

mariadb:
  enabled: true
  image:
    repository: bitnamilegacy/mariadb
    tag: "12.0.2"
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    existingSecret: application-application-secrets
    database: application-application
    username: application-application
  primary:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: do-block-storage
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
