namespace: ENC[AES256_GCM,data:0t86YuJ9u091z2Bq2wOr,iv:JFbSwdNtmAphJWRi7QY+yzs+SI8mquu0HOEVrtMCDfI=,tag:IKnf4xMwIfLa7R+eV/6XDQ==,type:str]
n8n_encryption_key: ENC[AES256_GCM,data:6u7eQA05LqfK2xjMGJK2arL9nw==,iv:eXSVID5uCI6tFyYWcJCPN3sqfzz9mH2VET9eL8dzl14=,tag:NaVfrTYCUJRWfZBvF9myxA==,type:str]
postgres_password: ENC[AES256_GCM,data:6omCUYnN97kQ1TL4,iv:lUY5KaVamzNmIdwkjulaypXK6WGnCjn8qQzWNwHAyFc=,tag:jQzX/3S7u/QKAbjRZSKr5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjzqkhmaqajahtvdgpgstn0q0edjjh8nykcnr2wge9qac8jnj4qq3lw5vp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaWordGtRRkZwM3p3Mkh6
            MGVxRlU1WUFOREhZOHZPWW1kUXRnRm9JdkEwCnp2NWxPTS9uaHVFL3dCb1kvT01S
            eFN5QjRsOExWMGFBUS9rMEc4OVJZUmcKLS0tIDk3NHozSzh5c1NYeVVseHk4SlVL
            elZoWE1pdEoySE4waGl6NlZkZjFDMVkKAt7lui10gAJtF+B3bEs5+lC0j8Sp2+nv
            FCCfAvPSPMZYJnR/rKUY3CPYz/Fqq5ekwcSgSxo5LqTHC1vqCXyhtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T10:05:38Z"
    mac: ENC[AES256_GCM,data:eq+0G5cG4sBJlYWWV82ZimsAyE/YWqDRL3gyVIUX4z36fhICuvEQpnicbH3nbV/W32iJ5MU6RvDZ/dPoQc+cpMHXaWzhhIxp552TlndgAVaM7iyFGOFFt/5yuJRVDmXWflnPHlnAZCqxIhjrLSn6yrOSg1sG7XcbwVNJLbkLL0w=,iv:EY0CVlrKCJKOi2IL1UPgFvTlKG7jYo9k3I2fDZYqzCs=,tag:Yy/lhNL2XL6Wryfw5nHr7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
