namespace: ENC[AES256_GCM,data:71+UfZ+PpvK9PYgCRieC,iv:7fifoL90cRuop1u32FPDg5u0g+c0AIhKNtZ8HqaX8RQ=,tag:9oGLWyXU6brB2oVbG3ItDw==,type:str]
n8n_encryption_key: ENC[AES256_GCM,data:/cZCEeZYeKbDgNKCdoKDNeYiwg==,iv:iJ/P8GQBWqZ/43h2pv+f33iOU1fORFN1U+86D1OMnTc=,tag:LicrpKcWAzzuivWAHELz4A==,type:str]
postgres_password: ENC[AES256_GCM,data:AWD+iVUpF7O9Ok/i,iv:XlTRwvX4q+B4J8RZtsTbhKdmb01P19cBvy7fvksfNHE=,tag:0B9y30ozuedQtVM0aOEfpg==,type:str]
TELEGRAM_API_KEY: ENC[AES256_GCM,data:CFmEWzVj5qt89ls9Z7vO8f0kAw/O+97tyknIsN8X6YKBSwkx42RPq1t/P7r/TA==,iv:OzlML+EVERwaKKnbvdLKg813Syg4PLBQZaxrrffjK9M=,tag:LgH0iBGOKs7qxYeSVi0bAw==,type:str]
OPENAI_API_KEY: ENC[AES256_GCM,data:C2SlFWkMUDUKBrz11bvuxmiMjjVT1NbbqKPKbK4bNi1tQrM1zk8/kpP53ux4nCUMLZcHd9MYlSbjCVrJb0EcyEa3jMs5q6DEUH+4HoWZc75YK99ldaf5fD1O19syUTYENQ+rIb/bsIVUwl1THbpiLPpip4arqWHxQPgZywBbz8BjtfTHuBizcZklSOQWJ65M08CnRGJhsFYuSGkpFrQPV7krZSM=,iv:Vv9NKhWXz+3LM+bKkztEmdDEQTlrZ9Ih7NmS/hfQd+g=,tag:ckQjUb6tb9ZXuec+k0Zk6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjzqkhmaqajahtvdgpgstn0q0edjjh8nykcnr2wge9qac8jnj4qq3lw5vp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYVY2NjZ6eEUxa3R4UHlZ
            S0V1YXN1bW1TVFlPakdZR3hoSnkzbUI1WVRRClhnV08wQzVucE5YeW9hLzNBWkEz
            MzdsM3VwNWlTaHc3WDBxU0RYQTV0REEKLS0tIFFxaUtwNVAwZGV2WEkrYzU2SDcw
            MTFkQWc5ZHM1QXRaUWVpQ1dtYjFHOVEK1u6Vza3ZdU48rmAU5afJW5hDMxBVgBfV
            veoogQnP0IHC/y2JW7Q1AyrKdvWGY11r+Jf5CKqofBlCaqI0wFe4Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T13:21:15Z"
    mac: ENC[AES256_GCM,data:BMaQGWkt8r4VDbecshLUc3hCq0QqYGuH/+WcN58RMx5oGHhWWvGJYmkqvOB141/f0lzrh3hELSE9J6gQ0JwGhRpcDc6E4DLdT9N+OQ/uw+8oJ2Yc/xgAnwMjtcG1hF7t/2FsVEtRxhq6+azy1NNX4BC+fjWG4M51sffjhbFBjS4=,iv:NF8LPL5qJVkWbjE0qjV+1axo549DlVuGu1OMV3ycMkk=,tag:6yDl/xPacWYus16zTbuM6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
