namespace: ENC[AES256_GCM,data:1R2o6qO5CfFGBaa3PkB5,iv:kZCO4yidhGVCc68av3DjQhHwnnWMXY7ltIqGVCAEujw=,tag:nTyYB9OagSNqlE8V16pr8Q==,type:str]
n8n_encryption_key: ENC[AES256_GCM,data:JlA6bmy73KSPNjih4G4ut6ft4w==,iv:fr5LRq1Dgj1zidZs1hzLEl9/Xh7v9fSFoiuazCS7QZ4=,tag:aFeRFQ5A7E4z+HzUW9Pd3w==,type:str]
postgres_password: ENC[AES256_GCM,data:BVwHeDwTmEW8hOyC,iv:a8B0ewrcNfNYe+j/+es8+ajthVZ2lOb1Zf769q4YLbQ=,tag:Xfvwm8q8zsNQVE06VP+eZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjzqkhmaqajahtvdgpgstn0q0edjjh8nykcnr2wge9qac8jnj4qq3lw5vp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZzdFcytpTU5ycVJkUllk
            dEZkbmRZWkQ2aGhuL0lwVDBWYkxHU2lHQ2w4CnVSMG9ZV3BtRlo3TitMWnZWMThk
            QmdBQlhLVUJWcHdDMHVlM05kODZFcXcKLS0tIG11bXZlOFpwS245amN1QnY4OG5D
            dzJBL2JvaVd2R3ZNeGhHaHhjZDI0TXcKngpujQwmCKoCcfkJkMTpfxqGCFv26gDQ
            n1uf0FfdWZesrPJbx82DgukevLg4QhervE+JJ9F/HZc6veiZ8N/BHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T10:03:26Z"
    mac: ENC[AES256_GCM,data:W2c2rgX9hUp6z7gaMew03yAhRImwd61sSqnXDlS2mb/ROWPkwo3+EqYyCgVuqVDDHzVKOWfHE+w7d2bbw8zyz1xFR7GxADRJEw9pI9Nu5GLQABprgNYmOf5YG6MRd+HZMmECzkh9TxYTmRqOTciYjQWTy8DME8dmcIC4JDJLeL8=,iv:4l6uknzV5keJjBA+4CGoeR2dZ9TpYKLHDYcFKRICAKI=,tag:1p4Bwp+b50ui3a+yJw95PA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
