apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  n8n-encryption-key: {{ .Values.n8n_encryption_key | b64enc | quote }}
  postgres-password: {{ .Values.postgres_password | b64enc | quote }}
