name: '[Workflow] On Source Change (PostgreSQL)'

concurrency:
  group: push-${{ github.branch }}-postgresql

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ops/helm/n8n-application-postgresql/**'
      - '.github/workflows/on_postgresql_change.yml'
jobs:
  deploy:
    name: 'Deploy'
    uses: webgrip/workflows/.github/workflows/helm-deploy.yml@main
    secrets:
      DIGITAL_OCEAN_API_KEY: ${{ secrets.DIGITAL_OCEAN_API_KEY }}
    with:
      environment: 'staging'
      path: './ops/helm/n8n-application-postgresql'


