namespace: n8n-application

_shared_config:
  hostname: &hostname n8n.k8s.nginx.webgrip.nl
  url: &url https://n8n.k8s.nginx.webgrip.nl

n8n:
  enabled: true
  image:
    repository: webgrip/n8n-application
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    className: nginx
    hosts:
      - host: *hostname
        paths:
          - /

    tls:
      - secretName: letsencrypt-nginx-n8n-application
        hosts:
          - *hostname
  main:
#    service:
#      type: ClusterIP
#      port: 5678
    config:
      n8n:
#        protocol: http
#        listenAddress: 0.0.0.0
#        port: 5678
        host: *hostname
        webhook_url: *url
        log_level: debug
        log_output: console,file
        log_file_location: /home/node/.n8n/logs/n8n.log
        metrics: true
        runners_enabled: true
        personalization_enabled: false
        enforce_settings_file_permissions: true
        templates_enabled: true
        hiring_banner_enabled: false
        queue_health_check_active: true
        node_env: production
        generic_timezone: Europe/Amsterdam
      db:
        type: sqlite
    secret:
      n8n:
        encryption_key: "your_encryption_key"

    extraEnv:
      DB_POSTGRESDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: n8n-application-secret
            key: n8n_secret1
