namespace: n8n-application

_shared_config:
  hostname: &hostname n8n.k8s.nginx.webgrip.nl
  url: &url https://n8n.k8s.nginx.webgrip.nl

n8n:
  enabled: true
  image:
    repository: webgrip/n8n-application
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    className: nginx
    hosts:
      - host: *hostname
        paths:
          - /

    tls:
      - secretName: letsencrypt-nginx-n8n-application
        hosts:
          - *hostname
  main:
    config:
      webhook_url: *url
      generic_timezone: Europe/Amsterdam
      node_env: production
      queue_health_check_active: true
      n8n:
        host: *hostname
        log_level: debug
        log_output: console,file
        log_file_location: /logs/n8n.log
        metrics: true
        runners_enabled: true
        personalization_enabled: false
        enforce_settings_file_permissions: true
        templates_enabled: true
        hiring_banner_enabled: false
      db:
        type: postgresdb
        postgresdb:
          host: n8n-application-postgresql.n8n-application.svc.cluster.local
          port: "5432"
          database: mydatabase
          user: myuser

    secret:
      n8n:
        encryption_key: "your_encryption_key"

    extraEnv:
      DB_POSTGRESDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgresql-secret
            key: password
